version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    user: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
volumes:
  db_data:
