scalar BigInt

type Liquity_Collateral {
  id: ID!
  trove: String!
  user: String!
  block: Int!
  balance: BigInt!
  count: Int!
  timestamp: Int!
}

type Liquity_Daily_Collateral {
  id: ID!
  trove: String!
  user: String!
  block: Int!
  balance: BigInt!
  timestamp: Int!
}
